### ISSUE TITLE
cocos2d v3.1

### ISSUE THREAD

**Issue by Sandbird** [danielgronlund/fancy-schmancy-joystick#1]
Doesnt work for the latest cocos2d :/
CCSpriteBatchNode is deprecated. Any chance for an easy fix ?

**Comment by danielgronlund** [comment]
The FancyJoystick class it self is actually compatible with v3.1. But in v3.1, to make it work, you need to add the joystick object as a child to a regular CCNode since there is no need for CCSpriteBatchNode in v3.1.

**Comment by Sandbird** [comment]
hmm, yeah thats what i did, but it didnt load the joystick..just the spritesheet, and put it onscreen.
I guess i am doing it wrong then...but how can i load the object when it was : 
_batch = [CCSpriteBatchNode batchNodeWithFile:@"joystick.png"];
[self addChild:_batch];
do you mean something like this ? : 
CCNode *joyst = [FancyJoystick alloc] init];
[self addchild: joyst];  //in my main scene.

(sorry not in front of a mac to test it...cant wait till tomorrow lol)

**Comment by danielgronlund** [comment]
Yes, either replace the CCSpriteBatchNode with a CCNode or add the joystick to self and it should work.

**Comment by Sandbird** [comment]
Yup that fixed it. Made a ccnode and add the _joystick as its child. Now they are happy playing in the backyard :P 
Thanks, and thanks for this lovely joystick :)

**Comment by danielgronlund** [comment]
Glad you like it, let me know if you publish any app that uses it!
